#!/bin/bash

ip=($(ip a | grep 192.168.))
gotip=${ip[1]}
payload="{\"msg\":This_is_test_Message_Form_Gaurav}";

mosquitto_pub -m ${payload} -h localhost -p 1883 -t "/6154359d5288e8424a94ec0a/outTopic" -P "92244@Great" -u "gv211432@gmail.com" -q 1

echo 

exit 0
