#!/bin/bash

ip=($(ip a | grep 192.168.))

#This line gets the 11th position word in the line contained by variable $ip
gotip=${ip[3]}
#gotip=${ip[11]}

reNewIp=${gotip:8}
no=$((${#reNewIp}-4))
myip=${reNewIp}
reqIp=${myip:0:${no}}

#curl 192.168.${reqIp}.221/button$1
firefox 192.168.${reqIp}.221
echo
exit 0
