#!/bin/bash

# if something is given
if [[ $1 != "" ]]
then
    # compiling the given file using tsc and output will be in same
    # dir with same name but different extention (i.e .js)
    tsc $1
    len=${#1}-3
    name=${1:0:len}
    # extracting the given name and running it with .js extention with nodejs
    node $name.js
else
    echo "No input files!!"
fi
